language: java
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  
script: mvn javadoc:javadoc doxygen:generate

before_install:
    - sudo apt-get update
    - sudo apt-get install doxygen
    

